apiVersion: apps/v1
kind: Deployment
metadata:
  name: intercity-backend
  namespace: intercity
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: intercity-backend
          resources:
            requests:
              cpu: 300m
              memory: 384Mi
            limits:
              cpu: 1500m
              memory: 1536Mi
