apiVersion: v1
kind: Service
metadata:
  name: intercity-backend
  namespace: intercity
  labels:
    app: intercity-backend
spec:
  type: ClusterIP
  selector:
    app: intercity-backend
  ports:
    - name: http
      port: 80
      targetPort: 3000
