apiVersion: apps/v1
kind: Deployment
metadata:
  name: intercity-backend
  namespace: intercity
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: intercity-backend
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 800m
              memory: 768Mi
