apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: intercity-staging
resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - migrate-job.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: intercity-backend
      namespace: intercity
  - path: migrate-job-patch.yaml
    target:
      kind: Job
      name: intercity-migrate
      namespace: intercity
images:
  - name: intercity-backend
    newName: ghcr.io/OWNER/REPO/intercity-backend
    newTag: staging
